version: '3.4'

services:
  skybot.api:
    image: ${DOCKER_REGISTRY}/skybotapi
    container_name: skybotapi
    build:
      context: .
      dockerfile: Skybot.Api/Dockerfile
    ports:
      - "80"
    environment:
      - DOCKER_REGISTRY
      - Authority
      - IntentThreshold
      - LuisApp__Endpoint
      - LuisApp__Key
      - TranslateApiCredentials__ApiKey


  skybot.spa:
    image: ${DOCKER_REGISTRY}/skybotspa
    container_name: skybotspa
    depends_on:
      - skybot.api
    build:
      context: .
      dockerfile: Skybot.Spa/Dockerfile

